production:
  clientes:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
    options:
      connect_timeout: 15
      max_pool_size: <%= ENV['MONGODB_MAX_POOL_SIZE'] %>
      retry_writes: true
development:
  clients:
    default:
      database: corydora_kanei_development
      hosts:
        - localhost:27017
      options:
test:
  clients:
    default:
      database: corydora_kanei_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
